include_recipe "ucsc-genomebrowser-cookbook::install_command"
include_recipe "ucsc-genomebrowser-cookbook::install_package"
include_recipe "ucsc-genomebrowser-cookbook::setup_source"
include_recipe "ucsc-genomebrowser-cookbook::restart_apache2"
include_recipe "ucsc-genomebrowser-cookbook::exec_ex_MySQLUserPerms_sh"
